FROM ubuntu:14.04.3 
MAINTAINER aherrera@spscommerce.com

USER root
RUN apt-get update &&\
    apt-get dist-upgrade -y &&\
    apt-get install -y \
    sudo \
    vim \
    curl \
    gcc \
    libyaml-dev \
    libpython2.7-dev \
    python-crypto \
    python-pip \
    apt-transport-https \
    jq \
    software-properties-common &&\
    apt-get clean &&\
    rm -rf /var/lib/apt/lists/*

RUN pip install \
    awscli \
    ansible==1.9.4 \
    credstash \
    boto

ADD . /tmp/playbook
WORKDIR /tmp/playbook
ENV ANSIBLE_FORCE_COLOR=true
ENV PYTHONUNBUFFERED=1
ENV AWS_ACCESS_KEY_ID={{aws_key_id}}
ENV AWS_SECRET_ACCESS_KEY={{aws_key}}

## run tests
RUN IDEMPOTENCE_RESULT=$( ansible-playbook -i "[test] localhost," -c local deploy.yml -e "environ=prod" 2>/dev/null ) &&\
    echo $IDEMPOTENCE_RESULT | grep -q 'changed=0.*failed=0' &&\
    (echo 'Idempotence test: \033[0;32mpass\033[0m' && exit 0) ||\
    (echo 'Idempotence test: \033[0;31mfail\033[0m' && echo "$IDEMPOTENCE_RESULT" && exit 1) 

EXPOSE 8080
CMD ["/usr/sbin/apache2ctl", "-D", "FOREGROUND"]
