- src: git+ssh://git@github.com/simplyadrian/ansible-role-cfn-stack.git
  name: stack
- src: git+ssh://git@github.com/simplyadrian/ansible-role-cfn-frontelb.git
  name: frontelb
- src: git+ssh://git@github.com/simplyadrian/ansible-role-module-credstash.git
  name: credstash
- src: git+ssh://git@github.com/geerlingguy/ansible-role-php.git
  name: php
- src: git+ssh://git@github.com/geerlingguy/ansible-role-apache.git
  name: apache
- src: git+ssh://git@github.com/simplyadrian/ansible-role-simpleinvoice.git
  name: simpleinvoice
